### ISSUE TITLE
psi_plot和csi_plot 的优化建议

### ISSUE THREAD

**Issue by hailee8899** [itlubber/scorecardpipeline#3]
（1）比如psi_plot的代码中：
df_psi = expected.merge(actual, on="分箱", how="outer").replace(np.nan, 0)

建议增加以下代码，按照 expected 中 "分箱" 列的顺序对 df_psi 进行排序，这样可以保证绘图后分箱中[负无穷，xx) 这一箱可以排在最左侧
df_psi = df_psi.sort_values(by="分箱", key=lambda x: x.map({v: i for i, v in enumerate(expected["分箱"])}))

（2）csi_plot 也是同理，建议也修改一下

**Comment by itlubber** [comment]
欢迎直接提pr哈，无论大小都是可以的😎

**Comment by itlubber** [comment]
> （1）比如psi_plot的代码中： df_psi = expected.merge(actual, on="分箱", how="outer").replace(np.nan, 0)
> 
> 建议增加以下代码，按照 expected 中 "分箱" 列的顺序对 df_psi 进行排序，这样可以保证绘图后分箱中[负无穷，xx) 这一箱可以排在最左侧 df_psi = df_psi.sort_values(by="分箱", key=lambda x: x.map({v: i for i, v in enumerate(expected["分箱"])}))
> 
> （2）csi_plot 也是同理，建议也修改一下

直接基于 [`feature_bin_stats`](https://scorecardpipeline.itlubber.art/scorecardpipeline.html#scorecardpipeline.ScoreCard.feature_bin_stats) 方法出来的分箱汇总信息应该是排好序的，然后传入 [`csi_plot`](https://scorecardpipeline.itlubber.art/scorecardpipeline.html#scorecardpipeline.csi_plot) 或者  [`psi_plot`](https://scorecardpipeline.itlubber.art/scorecardpipeline.html#scorecardpipeline.psi_plot) 里面，出来的结果理论上也是排好序的，所以可以不用在这里面进行排序 QaQ
