### ISSUE TITLE
WOE  计算公式问题

### ISSUE THREAD

**Issue by Roll113** [itlubber/scorecardpipeline#4]
大佬，请教下。
woe看公式似乎都是坏样本占比/好样本占比，而OptimalBinning和toad的包代码公式却是反过来了；scorecardpy这个包没有。目前有没有统一的做法，选哪个能更加直观的解释业务数据？

### OptimalBinning包结果
![image](https://github.com/user-attachments/assets/a4dfb221-6d64-40b9-8c34-fa8f82247d48)

### scorecardpipeline包结果
![image](https://github.com/user-attachments/assets/a9a532c3-27c3-4edd-a50f-6460a4ae99eb)

### scorecardpy包结果
![image](https://github.com/user-attachments/assets/432c99f4-4863-4c62-9d99-af46de7891c4)

### 当woe公式选择  坏样本占比/好样本占比 ； woe的结果似乎跟bad_rate 是一样的趋势的，会不会更好一点？

**Comment by itlubber** [comment]
理论上来讲无论是 `好样本占比` / `坏样本占比` 还是  `坏样本占比` / `好样本占比` 都是可以的，使用不同的方法计算出来的 `WOE` 的正负号有差异，在训练LR时系数的正负也会有差异，然后最终转评分卡的时候参数设置也有差异，但都是对应的。

由于 [`scorecardpipeline`](https://github.com/itlubber/scorecardpipeline/blob/main/scorecardpipeline/processing.py#L412) 中使用的分箱器主要一部分是基于 `toad` 封装的，所以与 `toad` 使用一样的  `好样本占比` / `坏样本占比` ，逻辑回顾模型系数都是正数，转评分卡时 `base_odds` 也是基于样本集的 `好样本占比` / `坏样本占比` 计算来的，如果使用相反的，那么后面的都反一下就行。

![image](https://github.com/user-attachments/assets/21c33537-79f6-473f-8350-df4be1b47ab0)

**Comment by itlubber** [comment]
可能大家比较熟悉的是 `坏样本占比` / `好样本占比`，在各类文章中也基本上是这种口径的，转完之后方向与坏率一致，更好解释

**Comment by Roll113** [comment]
是的，哪种口径计算都是可以的，这也只是正负号问题。就看个人偏好和习惯了。
